################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.c 

C_DEPS += \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.d 

OBJS += \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/%.o Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/%.su Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/%.cyclo: ../Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/%.c Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G431xx -DSTM32_THREAD_SAFE_STRATEGY=4 -c -I../Core/Inc -I../Middlewares/CMSIS-DSP/1.15.0/Include -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I../USB_Device/App -I../USB_Device/Target -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"D:/Embedded/MAV/CubeIDE/BSP/Inc" -I"D:/Embedded/MAV/CubeIDE/Control/Inc" -I../Core/ThreadSafe -include"D:/Embedded/MAV/CubeIDE/Middlewares/CMSIS-DSP/1.15.0/PrivateInclude/arm_sorting.h" -include"D:/Embedded/MAV/CubeIDE/Middlewares/CMSIS-DSP/1.15.0/Include/arm_math.h" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-CMSIS-2d-DSP-2f-1-2e-15-2e-0-2f-Source-2f-FilteringFunctions

clean-Middlewares-2f-CMSIS-2d-DSP-2f-1-2e-15-2e-0-2f-Source-2f-FilteringFunctions:
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctions.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/FilteringFunctionsF16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_fast_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_opt_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.o
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_partial_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_conv_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_fast_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_opt_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.cyclo
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_correlate_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_decimate_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_fast_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q31.su
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_init_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_lattice_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_fir_sparse_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_iir_lattice_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.d
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_norm_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Middlewares-2f-CMSIS-2d-DSP-2f-1-2e-15-2e-0-2f-Source-2f-FilteringFunctions

