################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.c \
../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.d \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.o \
./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/%.o Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/%.su Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/%.cyclo: ../Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/%.c Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G431xx -DSTM32_THREAD_SAFE_STRATEGY=4 -c -I../Core/Inc -I../Middlewares/CMSIS-DSP/1.15.0/Include -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I../USB_Device/App -I../USB_Device/Target -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"D:/Embedded/MAV/CubeIDE/BSP/Inc" -I"D:/Embedded/MAV/CubeIDE/Control/Inc" -I../Core/ThreadSafe -include"D:/Embedded/MAV/CubeIDE/Middlewares/CMSIS-DSP/1.15.0/PrivateInclude/arm_sorting.h" -include"D:/Embedded/MAV/CubeIDE/Middlewares/CMSIS-DSP/1.15.0/Include/arm_math.h" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-CMSIS-2d-DSP-2f-1-2e-15-2e-0-2f-Source-2f-StatisticsFunctions

clean-Middlewares-2f-CMSIS-2d-DSP-2f-1-2e-15-2e-0-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctions.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmax_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_absmin_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_accumulate_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_entropy_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_max_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.d
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mean_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_min_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_mse_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.cyclo
	-$(RM) ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_power_q7.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_rms_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_std_q31.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f16.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f32.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_f64.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q15.su ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.cyclo ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.d ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.o ./Middlewares/CMSIS-DSP/1.15.0/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Middlewares-2f-CMSIS-2d-DSP-2f-1-2e-15-2e-0-2f-Source-2f-StatisticsFunctions

